ferventcoder/chocolatey-packages

manual/kdiff3/kdiff3.nuspec, manual/kdiff3/tools/chocolateyInstall.ps1
Update kdiff3 to latest version (0.9.98)
=> kdiff3 0.9.98

manual/cruisecontrol.net/cruisecontrol.net.nuspec, manual/cruisecontrol.net/tools/chocolateyInstall.ps1
Also changed installChocolatey.ps1 layout based on feedback by Gary for other packages.
=> Update CruiseControl.NET to version 1.8.5.0

manual/ie9/ie9.nuspec, manual/ie9/tools/chocolateyInstall.ps1, manual/ie9/tools/install.ps1
and supports Vista + 7, and multiple languages.
=> IE9 is now silent and detects additional valid exit codes

automatic/vlc/tools/chocolateyInstall.ps1, automatic/vlc/vlc.ketarin.xml, automatic/vlc/vlc.nuspec
* Use the new download URLs (the previous mirror URLs didn't work anymore)
* Clean up the install script
* Clean up the nuspec
Please merge, import into Ketarin and push the new version.
Thanks
=> Fix vlc package

automatic/php/tools/chocolateyInstall.ps1
using Install-ChocolateyPath
Change initiated after request from users
=> make package "php" add its installation folder to user's path

automatic/vlc/vlc.ketarin.xml
As per https://twitter.com/etixxx/status/607854498451591168.
Should resolve #73.
=> #73 - Fix for VLC

manual/synergy/synergy.nuspec, manual/synergy/tools/chocolateyInstall.ps1
I'd like to help update Synergy to 1.7.3
=> Update Synergy to 1.7.3

manual/synergy/synergy.nuspec, manual/synergy/tools/chocolateyInstall.ps1
Let's update synergy again to 1.7.4
=> let's update synergy again

automatic/7zip.commandline/7zip.commandline.nuspec, automatic/7zip.commandline/tools/chocolateyInstall.ps1
Let me know if you want me to re-do this with it named 7zip.portable
=> 7zip.commandline fixes

manual/synergy/synergy.nuspec, manual/synergy/tools/chocolateyInstall.ps1
=> Update Synergy 1.7.5

automatic/sumatrapdf.commandline/sumatrapdf.commandline.nuspec, automatic/sumatrapdf.commandline/tools/chocolateyInstall.ps1, automatic/sumatrapdf.install/sumatrapdf.install.nuspec, automatic/sumatrapdf.install/tools/chocolateyInstall.ps1
You were using {{DownloadUrl}} and I wasn't quite sure that I could implement {{DownloadUrlx64}} without knowing your ketarin config. This uses {{PackageVersion}} and should seamlessly work.
=> new x64 release of sumatrapdf

manual/mingw/mingw.nuspec, manual/mingw/testPkg.ps1, manual/mingw/tools/chocolateyInclude.ps1, manual/mingw/tools/chocolateyInstall.ps1
Adds checksums for all files and a script to verify all the checksums are
correct and packages download.
=> Update to latest 4.8 release, fix consistency

automatic/vagrant/vagrant.nuspec
As pointed in https://chocolatey.org/packages/vagrant#comment-2524313735 and https://github.com/mitchellh/vagrant/issues/6754
=> Fix install dependency vcredist2010

automatic/git.install/tools/chocolateyInstall.ps1
Fix issue https://github.com/ferventcoder/chocolatey-packages/issues/93
=> package git: fix installation of icons and windows explorer integration

manual/ruby.portable/ruby.portable.nuspec, manual/ruby.portable/tools/chocolateyInstall.ps1, manual/ruby/ruby.nuspec, manual/ruby/tools/chocolateyInstall.ps1
Updating the ruby packages to install Ruby 2.3.0 which is the current stable version
=> Ruby 2.3.0 Update

manual/toggl/toggl.nuspec, manual/toggl/tools/chocolateyInstall.ps1
Also change install command to account to toggl's change to an exe installer rather than an msi and some updates to attribution in the nuspec file
=> update to 7.3.318

automatic/virtualbox/tools/chocolateyInstall.ps1
This should fix PATH issue #161.
=> fix for PATH issue #161

manual/ruby/ruby.nuspec, manual/ruby/tools/chocolateyInstall.ps1
I had no idea to test this patch. Someone should do this before merging.
=> Patch: Updated Ruby to 2.3.1

manual/ruby/tools/chocolateyInstall.ps1
Updates ruby to 2.3.3.
This should resolve the issues with `gem install`
=> Update Ruby to 2.3.3

automatic/mysql/mysql.nuspec
=> mysql: dependency on vcredist
