automatic/jetty/tools/chocolateyInstall.ps1

If you have a better fix than the "sleep 5" for the script to wait for Install-ChocolateyZipPackage, please let me know

jetty: fix move file command which starts too early. Fix output to console

---

automatic/notepadplusplus.commandline/notepadplusplus.commandline.ketarin.xml
automatic/notepadplusplus.install/notepadplusplus.install.ketarin.xml

The notepadplusplus* packages are currently broken, because the author changed the URL structure. Please merge this, import the updated ketarin jobs and update them in ketarin to release the fixed versions.

Fix download location of notepadplusplus* packages

---

automatic/notepadplusplus.commandline/notepadplusplus.commandline.ketarin.xml
automatic/notepadplusplus.commandline/notepadplusplus.commandline.nuspec
automatic/notepadplusplus.install/notepadplusplus.install.ketarin.xml
automatic/notepadplusplus.install/notepadplusplus.install.nuspec
automatic/notepadplusplus/notepadplusplus.nuspec

Updating urls for notepad++ to access the resources via HTTPS.

Notepad++ site is now https-only

---

automatic/notepadplusplus.commandline/notepadplusplus.commandline.ketarin.xml
automatic/notepadplusplus.install/notepadplusplus.install.ketarin.xml

The download page no longer contains the domain in the url - just the absolute link. Ketarin is now showing that there's an update available with this file.
I've modified the Ketarin files but, as before, I haven't exported my local copy of the Ketarin-produced file (I assume that your server does that?).
Thanks, Dan

Change the download folder variable regex to match new HTML

---

automatic/7zip.commandline/tools/chocolateyInstall.ps1

A mostly harmless bug - the package usually installs fine, but the downloaded zip is given a generic name ("Install.zip") and is placed in the root download cache directory, where it might collide with other packages exhibiting a similar bug.
````
DEBUG: Running 'Install-ChocolateyZipPackage' for  with
url:'http://www.7-zip.org/a/7z938-extra.7z', unzipLocation:
'C:\ProgramData\chocolatey\lib\7zip.commandline\tools\7zip', url64bit: '',
specificFolder: '', checksum: '', checksumType: '', checksum64: '',
checksumType64: ''
DEBUG: Running 'Get-ChocolateyWebFile' for  with
url:'http://www.7-zip.org/a/7z938-extra.7z',
fileFullPath:'C:\Users\Bla\AppData\Local\Temp\chocolatey\Install.zip',
````

7zip.commandline: fix typo in variable reference

---

automatic/sysinternals/tools/chocolateyInstall.ps1

Some internal corporate networks are blocking access to http://download.sysinternals.com/files/SysinternalsSuite.zip but https://download.sysinternals.com/files/SysinternalsSuite.zip works just fine.

Using https for fetching SysInternals

---

automatic/nodejs.commandline/tools/chocolateyInstall.ps1
automatic/nodejs.install/tools/chocolateyInstall.ps1

Probably the sligthly different schema in the download URL's might be the problem that there is no nodejs Chocolatey package for version 4.0.0.
Signed-off-by: Stefan Scherer <scherer_stefan@icloud.com>

Update links to nodejs 4.0.0

---

manual/ruby.portable/ruby.portable.nuspec
manual/ruby.portable/tools/chocolateyInstall.ps1

Update the ruby.portable package to the latest stable version of ruby, also enables checksum checking using MD5 values from the [ruby installer release notes.](https://bintray.com/oneclick/rubyinstaller/rubyinstaller/2.2.3/view#release).

Update ruby.portable to ruby 2.2.3

---

automatic/_output/git.install/2.6.4.20151216/git.install.nuspec
automatic/_output/git.install/2.6.4.20151216/tools/chocolateyInstall.ps1
automatic/git.install/tools/chocolateyInstall.ps1

If SYSTEM account is detected it strips 'icons\quicklaunch' from the feature list.  It also suppresses dialog boxes under system to generate an error rather than an eternal hang via dialog box.
This user folder does not exist for SYSTEM account profile and is not created on the fly by the installer (it assumes it is present as it would be for standard user profiles).  quicklaunch is technically depreciated.
Kills any instances of ssh-agent that are running from the git subfolder.
Displays to screen where to find log file in the case that an error is generated.  Should probably log this as well.
FYI - I hate it when choco packages don't [a] enable logging on the underlying installer, [b] tell where that log is because it is sometimes redirected by the fact of operating under choco - makes …

Fixes problems running under SYSTEM account and kills git's instance of ssh-agent

---

automatic/paint.net/paint.net.nuspec

Dependency is to the lowest (and only) non RC version of .NET 4.6

Add dependency to .NET 4.6 in Paint.NET package

---

automatic/_output/putty.install/0.63/tools/chocolateyInstall.ps1
automatic/_output/putty.install/0.64/tools/chocolateyInstall.ps1
automatic/_output/putty.install/0.65/tools/chocolateyInstall.ps1
automatic/_output/putty.install/0.66/tools/chocolateyInstall.ps1
automatic/_output/putty.portable/0.63/tools/chocolateyInstall.ps1
automatic/_output/putty.portable/0.64/tools/chocolateyInstall.ps1
automatic/_output/putty.portable/0.65/tools/chocolateyInstall.ps1
automatic/_output/putty.portable/0.66/tools/chocolateyInstall.ps1
ketarin/putty.install.ketarin.xml
ketarin/putty.portable.ketarin.xml

Putty currently has a download url with the version number as part of the url. The current code always used "latest". Because of this it is not possible to install an older version of putty, and it is currently not possible to install the most recent chocolatey version (0.66).

Putty version - fix download url

---

automatic/git.commandline/tools/chocolateyInstall.ps1

Fixes #85, adds `git-bash` shim. Also removes ssh conflict with `win32-openssh`.

git.commandline: only shim /cmd/git.exe and /git-bash.exe

---

automatic/sysinternals/tools/chocolateyInstall.ps1

This commit adds a package parameter of `/installpath:` which will install the
sysinternal tools to a non-default path.  Note that chocolatey will not be able
to uninstall sysinternals but will still succeed.

Add package parameter to install to custom directory

---

ketarin/nodejs.install.ketarin.xml

They've updated the nomenclature from "stable" to "current"
I don't know if this is related to the v6 package not being available yet (the URL that was there does redirect), but thought I'd update since I noticed.

Update nodejs.install script

---

automatic/git.install/git.install.nuspec
automatic/git.install/tools/chocolateyInstall.ps1

Added option `WindowsTerminal` which lets you install git without the MinTTY terminal so it just uses the regular windows terminal. 
Closes #88

Added windowsterminal opt to git

---

automatic/mysql/tools/chocolateyInstall.ps1

because cdn.mysql.com url does not work for previous versions
for example:
https://cdn.mysql.com/downloads/mysql-5.7/mysql-5.7.13-win32.zip - 404 error
https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.13-win32.zip - 200 ok

fix mysql download urls

---

automatic/_output/vagrant/1.7.3.20160919/tools/chocolateyinstall.ps1
automatic/_output/vagrant/1.7.3.20160919/tools/chocolateyuninstall.ps1
automatic/_output/vagrant/1.7.3.20160919/vagrant.nuspec
automatic/_output/vagrant/1.7.4.20160919/tools/chocolateyinstall.ps1
automatic/_output/vagrant/1.7.4.20160919/tools/chocolateyuninstall.ps1
automatic/_output/vagrant/1.7.4.20160919/vagrant.nuspec

This PR fixes #178 by updating the download links for Vagrant to the https://releases.hashicorp.com/ URL's.

Fix downloadlinks for Vagrant 1.7.x

---

automatic/nodejs.install.lts/nodejs.install.nuspec

Closes ferventcoder/chocolatey-packages#111 for nodejs.install.lts.
Apologies for the multiple PRs against a single issue. Working from the web client today.

Update NodeJS.install.lts Author and License

---

automatic/nodejs.install/nodejs.install.nuspec

Closes ferventcoder/chocolatey-packages#111 for nodejs.install.
Apologies for the multiple PRs against a single issue. Working from the web client today.

Update NodeJS.install Author and License

---

automatic/nodejs/nodejs.nuspec

Closes ferventcoder/chocolatey-packages#111 for nodejs virtual.
Apologies for the multiple PRs against a single issue. Working from the web client today.

Update Author and License URL

---

automatic/_output/adobereader/2015.007.20033/tools/chocolateyInstall.ps1

I know this is probably not the correct way, since you are using ketarin.
But the base package hasn't changed in 17 months and we could really use the checksum for automatic installs and upgrades.

(adobereader) base package checksum

---

manual/ruby2.devkit/tools/chocolateyInstall.ps1

I'm not completely sure, but it looks like this text was supposed to reference the Ruby 2 version of the package.

Fix reference to incorrect package in Ruby 2 DevKit

---

automatic/git.commandline/git.commandline.nuspec

In the migration of the Git packages to the core team repository I changed the ID of the `git.commandline` package to `git.portable`.
This PR changes the `git.commandline` package to a deprecated package for the [deprecation process](https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package).
Should be merged after https://github.com/chocolatey/chocolatey-coreteampackages/pull/489 was merged.

(git.commandline) Deprecate git.commandline package in favor of git.portable

---

ketarin/expresso.ketarin.xml

the new MSI is the same size as the old MSI.  
http://www.ultrapico.com/ExpressoDownload.htm Shows this full version as "Expresso 3.1 (Version 3.1.6224 - January 15, 2017*)" so I assume that the version detection will continue to work.

(Expresso) update FixedDownloadUrl to new MSI labeled as 3.1

---

manual/msbuild.communitytasks/msbuild.communitytasks.nuspec
manual/msbuild.communitytasks/tools/chocolateyInstall.ps1

In this PR I upgraded choco package to latest release [1.5.0.235](https://github.com/loresoft/msbuildtasks/releases/tag/1.5.0.235).

Upgrade MSBuild Community Tasks package to 1.5.0.235

---

ketarin/gitextensions.ketarin.xml

Previous match expression, while still apparently valid, was not evaluated correctly in Ketarin v1.8.7.0.

Modified GitExtensions to use a regular expression match for version.

---

automatic/_output/skype/7.38.0.101/skype.nuspec
automatic/_output/skype/7.38.0.101/tools/chocolateyInstall.ps1
automatic/_output/skype/7.38.0.101/tools/chocolateyUninstall.ps1
automatic/_output/skype/7.39.0.102/skype.nuspec
automatic/_output/skype/7.39.0.102/tools/chocolateyInstall.ps1
automatic/_output/skype/7.39.0.102/tools/chocolateyUninstall.ps1

adds Skype 7.39.0.102, includes previous update for Skype 7.38.0.101

Skype 7.39.0.102

---

manual/ruby2.devkit/ruby2.devkit.nuspec
manual/ruby2.devkit/tools/chocolateyInstall.ps1

Support optional InstallDir parameter.

---

manual/sharpkeys/sharpkeys.nuspec
manual/sharpkeys/tools/chocolateyInstall.ps1

Project was moved from CodePlex to GitHub. This packaging update reflects the change to the location but not the software version.

(sharpkeys) fix for project move to github

---

manual/keybase/tools/chocolateyinstall.ps1

Due to the keybase software sometimes need to reboot
and returns the exit code 3010 (Reboot needed), this change
should be added to the package.

(keybase) Added exit code 3010 as a valid exit code

---

manual/msi.template/templates/tools/chocolateyuninstall.ps1

This makes it easier on new-comers who use the templates from the VSCode Extension

Remove aliases from chocolateyuninstall.ps1.
